package exceptions;

public class Exception_Throw {

	/**
	 * @param args
	 * @throws Exception 
	 */
	public static void main(String[] args) throws Exception,ArithmeticException,InterruptedException{

		
		throw new Exception("Failed due to login");
		
		
	}

}
